export const carMakeColors: { [ make: string ]: string } = {
    Acura           : '#808080', 
    'Alfa Romeo'    : '#556b2f', 
    Alpine          : '#8b4513',  
    Ariel           : '#228b22', 
    'Aston Martin'  : '#8b0000',
    Audi            : '#808000', 
    Bentley         : '#483d8b', 
    BMW             : '#008080', 
    Bugatti         : '#4682b4', 
    Chevrolet       : '#000080', 
    Dodge           : '#9acd32',
    Ferrari         : '#32cd32',
    Ford            : '#daa520', 
    Jaguar          : '#7f007f', 
    Kia             : '#8fbc8f', 
    Koenigsegg      : '#d2b48c', 
    Lamborghini     : '#ff0000', 
    Lexus           : '#00ced1', 
    Lotus           : '#ff8c00',
    Maserati        : '#00ff00', 
    Mazda           : '#00fa9a', 
    McLaren         : '#8a2be2', 
    'Mercedes-Benz' : '#dc143c', 
    Nissan          : '#00bfff', 
    Pagani          : '#f4a460',
    Pininfarina     : '#0000ff',
    Polestar        : '#b0c4de', 
    Porsche         : '#ff00ff', 
    'Range Rover'   : '#1e90ff',
    Rimac           : '#db7093',
    'Rolls-Royce'   : '#f0e68c', 
    Shelby          : '#fa8072', 
    Subaru          : '#ffff54', 
    Tesla           : '#ffffff', 
    Toyota          : '#ff1493', 
    TVR             : '#7b68ee', 
    Ultima          : '#ee82ee', 
    Volkswagen      : '#7fffd4', 
    Volvo           : '#fdf5e6', 
    'W Motors'      : '#ffc0cb' 
};